# Generated by Django 3.2 on 2021-05-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearch',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
