# Generated by Django 3.2 on 2021-05-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_recentsearch_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite_wantto_visited_store',
            name='date_visited',
        ),
    ]
